export const EGYPTIAN_GOVERNORATES = [
    { en: "Cairo", ar: "القاهرة" },
    { en: "Giza", ar: "الجيزة" },
    { en: "Alexandria", ar: "الإسكندرية" },
    { en: "Dakahlia", ar: "الدقهلية" },
    { en: "Red Sea", ar: "البحر الأحمر" },
    { en: "Beheira", ar: "البحيرة" },
    { en: "Fayoum", ar: "الفيوم" },
    { en: "Gharbia", ar: "الغربية" },
    { en: "Ismailia", ar: "الإسماعيلية" },
    { en: "Menofia", ar: "المنوفية" },
    { en: "Minya", ar: "المنيا" },
    { en: "Qalyubia", ar: "القليوبية" },
    { en: "New Valley", ar: "الوادي الجديد" },
    { en: "Suez", ar: "السويس" },
    { en: "Sharqia", ar: "الشرقية" },
    { en: "South Sinai", ar: "جنوب سيناء" },
    { en: "North Sinai", ar: "شمال سيناء" },
    { en: "Beni Suef", ar: "بني سويف" },
    { en: "Port Said", ar: "بور سعيد" },
    { en: "Damietta", ar: "دمياط" },
    { en: "Kafr El Sheikh", ar: "كفر الشيخ" },
    { en: "Matrouh", ar: "مطروح" },
    { en: "Luxor", ar: "الأقصر" },
    { en: "Qena", ar: "قنا" },
    { en: "Sohag", ar: "سوهاج" },
    { en: "Aswan", ar: "أسوان" },
]

export const DOCTOR_SPECIALIZATIONS = [
    { en: "Psychiatrist", ar: "طبيب نفسي" },
    { en: "Psychologist", ar: "أخصائي نفسي" },
    { en: "Clinical Psychologist", ar: "أخصائي نفسي إكلينيكي" },
    { en: "Behavioral Therapist", ar: "معالج سلوكي" },
    { en: "Couples Counselor", ar: "استشاري علاقات زوجية" },
    { en: "Child Psychologist", ar: "أخصائي نفسي أطفال" },
    { en: "Addiction Specialist", ar: "متخصص علاج إدمان" },
]
